_prefs: 
  baselayer: null
  saveCenter: false
_properties: {}
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a> <a href='https://www.digitalglobe.com/' target='_blank'>&copy; DigitalGlobe</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -65.9039
  - -21.6892
  - 12
description: Vector contours + Mapbox Streets labels on a satellite base map
format: jpeg90
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: Satellite Contours and Labels
source: "mapbox:///mapbox.satellite,mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6"
styles: 
  - style.mss
  - satellite.mss
  - contour.mss
  - labels.mss
template: ''
